version: '3.9'

services:

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_backend
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery_worker
    command: celery -A src worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery_beat
    command: celery -A src beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  frontend:
    build:
      context: .
      dockerfile: frontend/rupaiyaa-new/Dockerfile
    container_name: react_native_frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/rupaiyaa-new:/app
    command: npx react-native start
