# Generated by Django 5.2.5 on 2025-09-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="The message to be sent as a reminder."),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        help_text="The date and time when the reminder should be triggered."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the reminder is still active."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Work", "Work"),
                            ("Personal", "Personal"),
                            ("Shopping", "Shopping"),
                            ("Finance", "Finance"),
                            ("Other", "Other"),
                        ],
                        default="General",
                        help_text="The category for this reminder.",
                        max_length=50,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user to whom this reminder is addressed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["due_date"],
            },
        ),
    ]
