# Generated by Django 5.2.5 on 2025-09-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("L", "Lend"), ("B", "Borrow")],
                        help_text="The type of transaction (Lend or Borrow).",
                        max_length=1,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of money transacted.",
                        max_digits=10,
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Annual interest rate in percentage.",
                        max_digits=5,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="The date the amount is due.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("A", "Accepted"), ("D", "Paid")],
                        default="P",
                        help_text="The current status of the transaction.",
                        max_length=1,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A brief description of the transaction."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        help_text="The user who initiated the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        help_text="The other user involved in the transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participated_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
