# Generated by Django 5.2.5 on 2025-09-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if both the initiator and the participant have verified the transaction.",
            ),
        ),
        migrations.CreateModel(
            name="TransactionVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verified_by_initiator",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the initiator has verified the transaction.",
                    ),
                ),
                (
                    "verified_by_participant",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the participant has verified the transaction.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="The transaction being verified.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="lend.transaction",
                    ),
                ),
            ],
        ),
    ]
