# Generated by Django 5.2.5 on 2025-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend", "0002_transaction_is_verified_transactionverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("L", "Lend")],
                help_text="The type of transaction (Lend or Borrow).",
                max_length=1,
            ),
        ),
    ]
