# Generated by Django 5.2.5 on 2025-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lend", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="verified_by_initiator",
            field=models.BooleanField(
                default=False,
                help_text="Whether the initiator has verified the transaction.",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="verified_by_participant",
            field=models.BooleanField(
                default=False,
                help_text="Whether the participant has verified the transaction.",
            ),
        ),
        migrations.DeleteModel(
            name="TransactionVerification",
        ),
    ]
