# Generated by Django 5.2.5 on 2025-09-02 10:53

import src.apps.chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="context_data",
            field=models.JSONField(
                blank=True, encoder=src.apps.chatbot.models.DecimalEncoder, null=True
            ),
        ),
    ]
