# Generated by Django 5.2.5 on 2025-09-02 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventexpense",
            name="paid_by",
            field=models.ForeignKey(
                default=1,
                help_text="The user who paid for this expense.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_expenses_paid",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
